
name: 'DockerAction-JANA2'
description: 'Build JANA2 and run tests'

# This specifies that docker will be used and the Dockerfile
# that the image should be built from. It assumes this is being
# done from a directory that already contains the source and
# that it is checked out to the correct branch. See the file
# JANA2/.github/workflows/ccpp-docker.yml for more details.
runs:
  using: 'docker'
  image: 'Dockerfile'
