#
# This specifies a custom GitHub action that is used to
# build a Docker image as part of the JANA2 CI.
#


name: 'DockerAction-JANA2'
description: 'Build JANA2 and run JTest plugin'

# This specifies that docker will be used and the Dockerfile that the
# image should be built from.
runs:
  using: 'docker'
  image: 'Dockerfile'
